import Head from "next/head";
import BasePage from "@/components/base-page";
import StatementForm from "@/components/statement-form";
import StatementOptionDropdown from "@/components/statement-option-dropdown";
import StatementTable from "@/components/statement-table";
import StatementYearSelect from "@/components/statement-year-select";

export default function Statements() {
  return (
    <>
      <Head>
        <title>Statements</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasePage>
        <div className="flex w-full flex-col gap-4">
          <div className="flex flex-row gap-4">
            <StatementOptionDropdown />
            <StatementYearSelect />
          </div>
          <StatementTable />
        </div>
        <StatementForm />
      </BasePage>
    </>
  );
}
