version: "3.8"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  background-job:
    container_name: background-job
    build:
      context: .
      dockerfile: ./apps/background-job/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - 3001:3001
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
