import Head from "next/head";
import BasePage from "@/components/base-page";
import CategoryForm, { CategoryFormAtom } from "@/components/category-form";
import CategoryTable from "@/components/category-table";
import TagForm, { TagFormAtom } from "@/components/tag-form";
import TagTable from "@/components/tag-table";
import { Button } from "@/components/ui/button";
import { useAtom } from "jotai";

export default function Categories() {
  const [, setCategoryFormValue] = useAtom(CategoryFormAtom);
  const [, setTagFormValue] = useAtom(TagFormAtom);

  return (
    <>
      <Head>
        <title>Categories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasePage>
        <div className="flex flex-row gap-2">
          <div className="flex w-full flex-col gap-4">
            <div className="flex gap-2">
              <Button onClick={() => setCategoryFormValue({ isOpen: true })} className="w-fit">
                Create Category
              </Button>
            </div>
            <CategoryTable />
          </div>
          <div className="flex w-full flex-col gap-4">
            <div className="flex gap-2">
              <Button onClick={() => setTagFormValue({ isOpen: true })} className="w-fit">
                Create Tag
              </Button>
            </div>
            <TagTable />
          </div>
        </div>
        <CategoryForm />
        <TagForm />
      </BasePage>
    </>
  );
}
