import Head from "next/head";
import BasePage from "@/components/base-page";
import { CategoryExpenseChart } from "@/components/category-expense-chart";

export default function Charts() {
  return (
    <>
      <Head>
        <title>Charts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasePage>
        <div className="grid grid-cols-12 gap-4">
          <div className="col-span-7 border border-gray-700 rounded-lg p-6">
            <CategoryExpenseChart />
          </div>
        </div>
      </BasePage>
    </>
  );
}
