import Head from "next/head";
import BasePage from "@/components/base-page";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasePage>
        <div />
      </BasePage>
    </>
  );
}
