version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  node-app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=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
